export const AccountTypes = {
    SAVINGS_ACCOUNT: 'SAVINGS_ACCOUNT',
    CURRENT_ACCOUNT: 'CURRENT_ACCOUNT',
    FIXED_SAVINGS_ACCOUNT: 'FIXED_SAVINGS_ACCOUNT',
  };
  
  export const AccountStatus = {
    ACTIVE: 'ACTIVE',
    DORMANT: 'DORMANT',
    FROZEN: 'FROZEN',
    UNDER_REVIEW: 'UNDER_REVIEW',
    // SUSPENDED: 'SUSPENDED',
    // DELETED: 'DELETED'
  }